x-common-application-variables: &common-application-variables
  DEBUG: "True"
  SECRET_KEY: "Unneeded"  # pragma: allowlist secret
  DJANGO_SETTINGS_MODULE: webcaf.settings
  DATABASE_URL: postgresql://webcaf:webcaf@postgres:5432/webcaf  # pragma: allowlist secret
  ENVIRONMENT: 'local'
  GOOGLE_ANALYTICS_ID: GTM-TEST

x-api-base: &api-base
  platform: linux/amd64
  build:
    context: .
    args:
      POETRY_ARGS: "--no-root --no-ansi"

services:
  web:
    platform: linux/amd64
    <<: *api-base
    ports:
      - "8000:8000"
    #Added the reload flag so the application will be reloaded when the source is modified.
    entrypoint: [ "/usr/local/bin/gunicorn", "webcaf.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120", "--access-logfile", "-", "--reload" ]
    environment:
      <<: *common-application-variables
      PYTHONBREAKPOINT: "ipdb.set_trace"
      SSO_MODE: dex
    volumes:
      - .:/app
      - webcaf_home:/home/webcaf
    depends_on:
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully
      oauth:
        condition: service_started

  postgres:
    platform: linux/amd64
    image: postgres
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: webcaf
      POSTGRES_PASSWORD: webcaf  # pragma: allowlist secret
      POSTGRES_DB: webcaf
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  oauth:
    image: ghcr.io/dexidp/dex:latest
    container_name: dex
    ports:
      - "5556:5556"  # Dex HTTP server
    volumes:
      - ./oauth-stub:/etc/dex
    command: ["dex", "serve", "/etc/dex/config.yaml"]

  init:
    <<: *api-base
    restart: 'no'
    environment:
      <<: *common-application-variables
      SSO_MODE: dex
    command: [ "sh", "/app/local-init.sh" ]
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: { }
  webcaf_home: { }
