x-common-application-variables: &common-application-variables
  DEBUG: "True"
  SECRET_KEY: "Unneeded"  # pragma: allowlist secret
  DJANGO_SETTINGS_MODULE: django_govuk.settings
  DATABASE_URL: postgresql://django_govuk:django_govuk@postgres:5432/django_govuk  # pragma: allowlist secret
  ENVIRONMENT: 'local'
  GOOGLE_ANALYTICS_ID: GTM-TEST

x-api-base: &api-base
  platform: linux/amd64
  build:
    context: .
    args:
      POETRY_ARGS: "--no-root --no-ansi"

services:
  web:
    platform: linux/amd64
    <<: *api-base
    ports:
      - "8010:8000"
    #Added the reload flag so the application will be reloaded when the source is modified.
    entrypoint: [ "/usr/local/bin/gunicorn", "django_govuk.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120", "--access-logfile", "-", "--reload" ]
    environment:
      <<: *common-application-variables
    volumes:
      - .:/app
      - django_govuk_home:/home/django_govuk
    depends_on:
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully

  postgres:
    platform: linux/amd64
    image: postgres
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: django_govuk
      POSTGRES_PASSWORD: django_govuk  # pragma: allowlist secret
      POSTGRES_DB: django_govuk
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  init:
    <<: *api-base
    restart: 'no'
    environment:
      <<: *common-application-variables
    command: [ "sh", "/app/local-init.sh" ]
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: { }
  django_govuk_home: { }
