# Generated by Django 5.1.9 on 2025-07-31 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_data", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "organisation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ad-hoc-advisory-group", "Ad-hoc advisory group"),
                            ("advisory-non-departmental-public-body", "Advisory non-departmental public body"),
                            ("civil-service", "Civil service"),
                            ("executive-agency", "Executive agency"),
                            ("executive-non-departmental-public-body", "Executive non-departmental public body"),
                            ("executive-office", "executive office"),
                            ("independent-monitoring-body", "Independent monitoring body"),
                            ("ministerial-department", "Ministerial department"),
                            ("non-ministerial-department", "Non-ministerial department"),
                            ("public-corporation", "Public corporation"),
                            ("special-health-authority", "Special health authority"),
                            ("tribunal", "Tribunal"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "parent_organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_organisations",
                        to="webcaf.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="systems", to="webcaf.organisation"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "organisation")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cyber_advisor", "Cyber advisor"),
                            ("govassure_lead", "GovAssure Lead"),
                            ("organisation_user", "Organisation user"),
                        ],
                        default="User",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="webcaf.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=255,
                    ),
                ),
                (
                    "caf_profile",
                    models.CharField(
                        choices=[("baseline", "Baseline"), ("enhanced", "Enhanced")], default="baseline", max_length=255
                    ),
                ),
                ("assessment_period", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("assessments_data", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="webcaf.system"
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment_period", "system", "status")},
            },
        ),
    ]
