# Generated by Django 5.1.9 on 2025-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="version",
            field=models.CharField(default="v3.2", max_length=10),
            preserve_default=False,
        ),
    ]
