# Generated by Django 5.1.9 on 2025-07-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="parent_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_organisations",
                to="webcaf.organisation",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
