# Generated by Django 5.1.9 on 2025-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0002_organisation_organisation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact_role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(
                blank=True,
                choices=[("Government", "Government"), ("Public", "Public")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True, choices=[("Admin", "Admin"), ("User", "User")], default="User", max_length=255, null=True
            ),
        ),
    ]
