# Generated by Django 5.1.9 on 2025-09-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0002_assessment_version_system_hosting_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="reference",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
