# Generated by Django 5.1.9 on 2025-08-19 10:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0002_assessment_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="hosting_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("hosted_on_premises", "On premises"),
                    ("hosted_on_cloud", "Cloud hosted"),
                    ("hosted_hybrid", "Hybrid"),
                    ("hosted_by_third_party", "Commercially hosted by third-party"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="internet_facing",
            field=models.CharField(blank=True, choices=[("yes", "Yes"), ("no", "No")], null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="last_assessed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assessed_in_2324", "Yes, assessed in 2023/24"),
                    ("assessed_in_2425", "Yes, assessed in 2024/25"),
                    ("assessed_in_2324_and_2425", "Yes, assessed in both 2023/24 and 2024/25"),
                    ("assessed_not_done", "No"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="system_owner",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("owned_by_organisation_being_assessed", "The organisation being assessed"),
                    ("owned_by_another_government_organisation", "Another government organisation"),
                    ("owned_by_third_party_company", "Third-party company"),
                    ("owned_by_other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="system_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("directly_supports_organisation_mission", "The system directly supports the organisation mission"),
                    (
                        "supports_other_critical_systems",
                        "The system is a corporate or enterprise system or network that supports other critical systems",
                    ),
                    (
                        "is_critical_for_day_to_day_operations",
                        "The system is a corporate or enterprise system deemed critical for day-to-day operations",
                    ),
                    (
                        "hosted_externally_or_by_commercial_providers_or_other_departments",
                        "The system is hosted externally, including by commercial providers or other departments",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
