# Generated by Django 5.1.9 on 2025-07-24 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0003_organisation_contact_email_organisation_contact_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="profiles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
