# Generated by Django 5.1.9 on 2025-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0003_system_hosting_type_system_internet_facing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "Cyber advisor"),
                    ("govassure_lead", "GovAssure lead"),
                    ("organisation_user", "Organisation user"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
