# Generated by Django 5.1.9 on 2025-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0003_assessment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="framework",
            field=models.CharField(
                choices=[("caf32", "Cyber Assessment Framework v3.2"), ("caf40", "Cyber Assessment Framework v4.0")],
                default="caf32",
                max_length=255,
            ),
        ),
    ]
