# Generated by Django 5.1.9 on 2025-09-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0004_assessment_framework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="reference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
