# Generated by Django 5.1.9 on 2025-07-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0004_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_data", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="system",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ad-hoc-advisory-group", "Ad-hoc advisory group"),
                    ("advisory-non-departmental-public-body", "Advisory non-departmental public body"),
                    ("civil-service", "Civil service"),
                    ("executive-agency", "Executive agency"),
                    ("executive-non-departmental-public-body", "Executive non-departmental public body"),
                    ("executive-office", "executive office"),
                    ("independent-monitoring-body", "Independent monitoring body"),
                    ("ministerial-department", "Ministerial department"),
                    ("non-ministerial-department", "Non-ministerial department"),
                    ("public-corporation", "Public corporation"),
                    ("special-health-authority", "Special health authority"),
                    ("tribunal", "Tribunal"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "Cyber advisor"),
                    ("govassure_lead", "GovAssure Lead"),
                    ("organisation_user", "Organisation user"),
                ],
                default="User",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("assessment_period", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="webcaf.system"
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment_period", "system", "status")},
            },
        ),
    ]
