# Generated by Django 5.1.9 on 2025-07-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0004_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_data", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="system",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ad-hoc advisory group", "Ad-hoc advisory group"),
                    ("Advisory non-departmental public body", "Advisory non-departmental public body"),
                    ("Civil service", "Civil service"),
                    ("Executive agency", "Executive agency"),
                    ("Executive non-departmental public body", "Executive non-departmental public body"),
                    ("Executive office", "Executive office"),
                    ("Independent monitoring body", "Independent monitoring body"),
                    ("Ministerial department", "Ministerial department"),
                    ("Non-ministerial department", "Non-ministerial department"),
                    ("Public corporation", "Public corporation"),
                    ("Special health authority", "Special health authority"),
                    ("Tribunal", "Tribunal"),
                    ("Other", "Other"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cyber advisor", "Cyber advisor"),
                    ("GovAssure Lead", "GovAssure Lead"),
                    ("Organisation user", "Organisation user"),
                ],
                default="User",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("assessment_period", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="webcaf.system"
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment_period", "system", "status")},
            },
        ),
    ]
