# Generated by Django 5.1.9 on 2025-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0005_configuration_system_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
