# Generated by Django 5.1.9 on 2025-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0005_alter_assessment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="review_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("independent", "Independent assurance review"),
                    ("peer_review", "Peer review"),
                    ("self_assessment", "No review, self-assessment only"),
                    ("not_decided", "Not decided"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
