# Generated by Django 5.1.9 on 2025-09-16 06:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0006_assessment_review_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="version",
        ),
        migrations.CreateModel(
            name="HistoricalAssessment",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=255,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("caf32", "Cyber Assessment Framework v3.2"),
                            ("caf40", "Cyber Assessment Framework v4.0"),
                        ],
                        default="caf32",
                        max_length=255,
                    ),
                ),
                (
                    "caf_profile",
                    models.CharField(
                        choices=[("baseline", "Baseline"), ("enhanced", "Enhanced")], default="baseline", max_length=255
                    ),
                ),
                ("assessment_period", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(blank=True, editable=False)),
                ("last_updated", models.DateTimeField(blank=True, editable=False)),
                ("assessments_data", models.JSONField(default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="webcaf.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical assessment",
                "verbose_name_plural": "historical assessments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
