# Generated by Django 5.1.9 on 2025-07-28 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0007_assessment_creating_user_assessment_last_updated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessment",
            old_name="creating_user",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="assessment",
            old_name="last_updated_user",
            new_name="last_updated_by",
        ),
    ]
