# Generated by Django 5.1.9 on 2025-09-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0007_remove_assessment_version_historicalassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalassessment",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("independent", "Independent assurance review"),
                    ("peer_review", "Peer review"),
                    ("self_assessment", "No review, self-assessment only"),
                    ("not_decided", "Not decided"),
                ],
                default="not_decided",
                max_length=255,
            ),
        ),
    ]
