# Generated by Django 5.1.9 on 2025-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0008_historicalassessment_review_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ad-hoc-advisory-group", "Ad-hoc advisory group"),
                    ("advisory-non-departmental-public-body", "Advisory non-departmental public body"),
                    ("agencies-other-public-bodies", "Agencies and other public bodies"),
                    ("devolved-administrations", "Devolved administrations"),
                    ("executive-agency", "Executive agency"),
                    ("executive-non-departmental-public-body", "Executive non-departmental public body"),
                    ("executive-office", "Executive office"),
                    ("high-profile-groups", "High profile groups"),
                    ("ministerial-department", "Ministerial department"),
                    ("non-ministerial-department", "Non-ministerial department"),
                    ("public-corporation", "Public corporation"),
                    ("tribunal", "Tribunal"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
