# Generated by Django 5.1.9 on 2025-07-28 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0008_rename_creating_user_assessment_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessment",
            old_name="start_date",
            new_name="created_on",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="name",
        ),
    ]
