# Generated by Django 5.1.12 on 2025-10-02 15:00

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0009_alter_organisation_organisation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="internet_facing",
        ),
        migrations.AddField(
            model_name="system",
            name="corporate_services",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("email_and_communication", "Email and communication"),
                    ("office_productivity", "Office productivity"),
                    ("document_storage_and_management", "Document storage and management"),
                    ("hr", "HR"),
                    ("payroll", "Payroll"),
                    ("procurement_and_contract_management", "Procurement and contract management"),
                    ("customer_relationship_management", "Customer relationship management"),
                    ("help_desk_it_support", "Help desk / IT support"),
                    ("data_management_analytics", "Data management / analytics"),
                    ("other", "Other"),
                    ("none", "None of the above"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="hosting_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("hosted_on_premises", "On premises"),
                    ("hosted_on_cloud", "Cloud hosted"),
                    ("hosted_hybrid", "Hybrid"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="last_assessed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assessed_in_2324", "Yes, in 2023/24"),
                    ("assessed_in_2425", "Yes, in 2024/25"),
                    ("assessed_in_2324_and_2425", "Yes, in both 2023/24 and 2024/25"),
                    ("assessed_not_done", "No, it has not been assessed before"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="system_owner",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("owned_by_organisation_being_assessed", "The organisation being assessed"),
                    ("owned_by_another_government_organisation", "Another government organisation"),
                    ("owned_by_third_party_company", "Third-party company"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="system_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("directly_delivers_public_services", "It directly delivers public services"),
                    (
                        "supports_other_critical_systems",
                        "It provides core infrastructure essential for other critical systems to function",
                    ),
                    (
                        "is_critical_for_day_to_day_operations",
                        "It provides corporate services or functions required for day-to-day operations for example, payroll",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
