# Generated by Django 5.1.9 on 2025-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0009_rename_start_date_assessment_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="caf_profile",
            field=models.CharField(
                choices=[("basic", "basic"), ("enhanced", "enhanced")], default="basic", max_length=255
            ),
        ),
    ]
