# Generated by Django 5.1.9 on 2025-07-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0010_assessment_caf_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="caf_profile",
            field=models.CharField(
                choices=[("baseline", "baseline"), ("enhanced", "enhanced")], default="baseline", max_length=255
            ),
        ),
    ]
