# Generated by Django 5.1.12 on 2025-10-03 16:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0010_remove_system_internet_facing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="corporate_services",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("email_and_communication", "Email and communication"),
                    ("office_productivity", "Office productivity"),
                    ("document_storage_and_management", "Document storage and management"),
                    ("hr", "HR"),
                    ("payroll", "Payroll"),
                    ("procurement_and_contract_management", "Procurement and contract management"),
                    ("customer_relationship_management", "Customer relationship management"),
                    ("help_desk_it_support", "Help desk / IT support"),
                    ("data_management_analytics", "Data management / analytics"),
                    ("none", "None of the above"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
