# Generated by Django 5.1.9 on 2025-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0011_alter_system_corporate_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="reference",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="system",
            name="reference",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="reference",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalassessment",
            name="reference",
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
