# Generated by Django 5.1.9 on 2025-07-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0011_alter_assessment_caf_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
