# Generated by Django 5.1.9 on 2025-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0012_alter_assessment_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="caf_profile",
            field=models.CharField(
                choices=[("baseline", "Baseline"), ("enhanced", "Enhanced")], default="baseline", max_length=255
            ),
        ),
    ]
