# Generated by Django 5.1.13 on 2025-10-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0012_organisation_reference_system_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ad-hoc-advisory-group", "Ad-hoc advisory group"),
                    ("advisory-non-departmental-public-body", "Advisory non-departmental public body"),
                    ("agency-or-other-public-body", "Agency or other public body"),
                    ("devolved-administration", "Devolved administration"),
                    ("executive-agency", "Executive agency"),
                    ("executive-non-departmental-public-body", "Executive non-departmental public body"),
                    ("executive-office", "Executive office"),
                    ("high-profile-group", "High profile group"),
                    ("ministerial-department", "Ministerial department"),
                    ("non-ministerial-department", "Non-ministerial department"),
                    ("public-corporation", "Public corporation"),
                    ("tribunal", "Tribunal"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
