# Generated by Django 5.1.13 on 2025-10-10 08:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0013_alter_organisation_organisation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="hosting_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("hosted_on_premises", "On-premises"),
                    ("hosted_on_cloud", "Cloud hosted"),
                    ("hosted_hybrid", "Hybrid"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
