# Generated by Django 5.1.13 on 2025-10-21 13:38

from django.db import migrations, models


def set_default_config_values(apps, schema_editor):
    Configuration = apps.get_model("webcaf", "Configuration")
    Configuration.objects.create(
        name="default",
        config_data={
            "default_framework": "caf32",
            "current_assessment_period": "25/26",
            "assessment_period_end": "31 March 2026 11:59pm",
        },
    )
    Configuration.objects.create(
        name="26/27",
        config_data={
            "default_framework": "caf32",
            "current_assessment_period": "26/27",
            "assessment_period_end": "31 March 2027 11:59pm",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0015_historicalorganisation_historicalsystem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="name",
            field=models.CharField(default="default", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(code=set_default_config_values, reverse_code=migrations.RunPython.noop),
    ]
