# Generated by Django 5.1.13 on 2025-10-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0016_configuration_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="submission_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalassessment",
            name="submission_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
