# Generated by Django 5.1.13 on 2025-10-28 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("otp_email", "0006_add_timestamps"),
        ("webcaf", "0017_assessment_submission_due_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovNotifyEmailDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_email.emaildevice",),
        ),
    ]
