# Generated by Django 5.1.13 on 2025-11-14 12:36

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0018_govnotifyemaildevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsystem",
            name="corporate_services_other",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="corporate_services_other",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsystem",
            name="corporate_services",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("email_and_communication", "Email and communication"),
                    ("office_productivity", "Office productivity"),
                    ("document_storage_and_management", "Document storage and management"),
                    ("hr", "HR"),
                    ("payroll", "Payroll"),
                    ("financial_and_accounting", "Financial and accounting"),
                    ("procurement_and_contract_management", "Procurement and contract management"),
                    ("customer_relationship_management", "Customer relationship management"),
                    ("help_desk_it_support", "Help desk / IT support"),
                    ("data_management_analytics", "Data management / analytics"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="corporate_services",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("email_and_communication", "Email and communication"),
                    ("office_productivity", "Office productivity"),
                    ("document_storage_and_management", "Document storage and management"),
                    ("hr", "HR"),
                    ("payroll", "Payroll"),
                    ("financial_and_accounting", "Financial and accounting"),
                    ("procurement_and_contract_management", "Procurement and contract management"),
                    ("customer_relationship_management", "Customer relationship management"),
                    ("help_desk_it_support", "Help desk / IT support"),
                    ("data_management_analytics", "Data management / analytics"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
