# Generated by Django 5.1.15 on 2025-12-22 12:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import webcaf.webcaf.models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0019_historicalsystem_corporate_services_other_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "GDS cyber advisor"),
                    ("organisation_lead", "GovAssure lead"),
                    ("organisation_user", "Organisation user"),
                    ("reviewer", "Peer reviewer"),
                    ("assessor", "Independent assurance reviewer"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "GDS cyber advisor"),
                    ("organisation_lead", "GovAssure lead"),
                    ("organisation_user", "Organisation user"),
                    ("reviewer", "Peer reviewer"),
                    ("assessor", "Independent assurance reviewer"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalReview",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_on", models.DateTimeField(blank=True, editable=False)),
                ("last_updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To do"),
                            ("in_progress", "In-progress"),
                            ("clarify", "Clarify"),
                            ("completed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="to_do",
                        max_length=25,
                    ),
                ),
                ("review_data", models.JSONField(blank=True, default=dict)),
                ("reference", models.CharField(db_index=True, max_length=20, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="webcaf.assessment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical review",
                "verbose_name_plural": "historical reviews",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To do"),
                            ("in_progress", "In-progress"),
                            ("clarify", "Clarify"),
                            ("completed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="to_do",
                        max_length=25,
                    ),
                ),
                ("review_data", models.JSONField(blank=True, default=dict)),
                ("reference", models.CharField(max_length=20, null=True, unique=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="webcaf.assessment"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "unique_together": {("assessment",)},
            },
            bases=(webcaf.webcaf.models.ReferenceGeneratorMixin, models.Model),
        ),
    ]
