# Generated by Django 5.1.13 on 2025-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0021_alter_historicalreview_status_alter_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreview",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To do"),
                    ("in_progress", "In-progress"),
                    ("clarify", "Clarify"),
                    ("completed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="to_do",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To do"),
                    ("in_progress", "In-progress"),
                    ("clarify", "Clarify"),
                    ("completed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="to_do",
                max_length=25,
            ),
        ),
    ]
