# Generated by Django 5.1.13 on 2025-12-16 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0022_alter_historicalreview_status_alter_review_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessor",
            name="last_updated_by",
        ),
        migrations.RemoveField(
            model_name="assessor",
            name="members",
        ),
        migrations.RemoveField(
            model_name="assessor",
            name="organisation",
        ),
        migrations.RemoveField(
            model_name="historicalreview",
            name="assessed_by",
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("assessment",)},
        ),
        migrations.DeleteModel(
            name="HistoricalAssessor",
        ),
        migrations.RemoveField(
            model_name="review",
            name="assessed_by",
        ),
        migrations.DeleteModel(
            name="Assessor",
        ),
    ]
