# Generated by Django 5.1.13 on 2025-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0023_remove_assessor_last_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "GDS cyber advisor"),
                    ("organisation_lead", "GovAssure lead"),
                    ("organisation_user", "Organisation user"),
                    ("reviewer", "Peer reviewer"),
                    ("assessor", "Independent assurance reviewer"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "GDS cyber advisor"),
                    ("organisation_lead", "GovAssure lead"),
                    ("organisation_user", "Organisation user"),
                    ("reviewer", "Peer reviewer"),
                    ("assessor", "Independent assurance reviewer"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
