# Generated by Django 5.1.15 on 2026-03-10 14:49

from django.db import migrations


def update_default_config_values(apps, schema_editor):
    Configuration = apps.get_model("webcaf", "Configuration")
    default_config = Configuration.objects.get(name="default")
    next_config = Configuration.objects.get(
        name="26/27",
    )

    # Change the assessment period and banner display dates for the current assessment period
    default_config.config_data["assessment_period_end"] = "31 August 2026 11:59pm"
    default_config.config_data["banner_display_until"] = "31 March 2026 11:59pm"
    default_config.save()
    if next_config:
        # Change the assessment period and banner display dates for the next assessment period
        next_config.config_data["assessment_period_end"] = "31 August 2027 11:59pm"
        next_config.config_data["banner_display_until"] = "31 March 2027 11:59pm"
        next_config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0024_alter_historicaluserprofile_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuration",
            options={"verbose_name": "Configuration", "verbose_name_plural": "Configurations"},
        ),
        migrations.AlterUniqueTogether(
            name="configuration",
            unique_together={("name",)},
        ),
        migrations.RunPython(code=update_default_config_values, reverse_code=migrations.RunPython.noop),
    ]
