# Generated by Django 5.1.15 on 2026-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0025_update_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "Cyber advisor"),
                    ("organisation_lead", "GovAssure lead"),
                    ("organisation_user", "Organisation user"),
                    ("reviewer", "Peer reviewer"),
                    ("assessor", "Independent assurance reviewer"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cyber_advisor", "Cyber advisor"),
                    ("organisation_lead", "GovAssure lead"),
                    ("organisation_user", "Organisation user"),
                    ("reviewer", "Peer reviewer"),
                    ("assessor", "Independent assurance reviewer"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
