# Generated by Django 5.1.15 on 2026-05-07 12:28

from django.db import migrations, models


def init_settings(apps, schema_editor):
    Settings = apps.get_model("webcaf", "Settings")
    # This will create the instance if not present in the database
    Settings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0026_alter_historicaluserprofile_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("admin_verification_enabled", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [models.CheckConstraint(name="single_row_only", check=models.Q(("pk", 1)))],
            },
        ),
        migrations.RunPython(code=init_settings, reverse_code=migrations.RunPython.noop),
    ]
