# Generated by Django 5.1.15 on 2026-05-28 12:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import webcaf.webcaf.models


def init_tips(apps, schema_editor):
    Tip = apps.get_model("webcaf", "Tip")
    Review = apps.get_model("webcaf", "Review")
    # This will create the instance if not present in the database
    for review in Review.objects.all():
        if review.status == "completed":
            tip, created = Tip.objects.get_or_create(review=review)
            if created:
                tip.save()
                print(f"Created tip {tip.reference} for review {review.id}")


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0027_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTip",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_on", models.DateTimeField(blank=True, editable=False)),
                ("last_updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To do"),
                            ("in_progress", "In-progress"),
                            ("completed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="to_do",
                        max_length=25,
                    ),
                ),
                ("tip_data", models.JSONField(blank=True, default=dict)),
                ("reference", models.CharField(db_index=True, max_length=20, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="webcaf.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tip",
                "verbose_name_plural": "historical tips",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To do"),
                            ("in_progress", "In-progress"),
                            ("completed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="to_do",
                        max_length=25,
                    ),
                ),
                ("tip_data", models.JSONField(blank=True, default=dict)),
                ("reference", models.CharField(max_length=20, null=True, unique=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tip", to="webcaf.review"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "unique_together": {("review",)},
            },
            bases=(webcaf.webcaf.models.ReferenceGeneratorMixin, models.Model),
        ),
        migrations.RunPython(code=init_tips, reverse_code=migrations.RunPython.noop),
    ]
