# Generated by Django 5.1.15 on 2026-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0028_historicaltip_tip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltip",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To do"),
                    ("in_progress", "In-progress"),
                    ("review", "Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="to_do",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="tip",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To do"),
                    ("in_progress", "In-progress"),
                    ("review", "Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="to_do",
                max_length=25,
            ),
        ),
    ]
