# Generated by Django 5.1.15 on 2026-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0029_alter_historicaltip_status_alter_tip_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="gov_assure_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        # Update the gov_assure_email field in the settings table with the value from the configuration table
        # I have decided to move the email to settings as the config object is mainly used for
        # CAF related information
        migrations.RunSQL(
            sql="""
                              update webcaf_settings
                              set gov_assure_email = (select config_data ->> 'gov_assure_email'
                                                      from webcaf_configuration
                                                      order by id
                                                      limit 1)
                              WHERE id = 1;
                              """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
