# Generated by Django 5.1.15 on 2026-06-30 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0031_alter_historicaltip_status_alter_tip_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tip",
            options={
                "ordering": ["-created_on"],
                "permissions": (("can_approve_tip", "Can approve tips"), ("can_reject_tip", "Can reject tips")),
            },
        ),
    ]
