# Generated by Django 5.1.15 on 2026-07-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webcaf", "0032_alter_tip_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="tip_max_words_main",
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name="settings",
            name="tip_max_words_other",
            field=models.IntegerField(default=1000),
        ),
    ]
