# Generated by Django 5.1.15 on 2026-09-16 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def init_user_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    # This will create the instance if not present in the database
    Group.objects.get_or_create(name="admin")
    Group.objects.get_or_create(name="data analyst admin")
    Group.objects.get_or_create(name="data analyst")
    Group.objects.get_or_create(name="cyber advisor")


class Migration(migrations.Migration):

    dependencies = [
        ("webcaf", "0033_settings_tip_max_words"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "backend_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frontend_association",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "frontend_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backend_association",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("backend_user", "frontend_user")},
            },
        ),
        migrations.RunPython(code=init_user_groups, reverse_code=migrations.RunPython.noop),
    ]
