issuer: http://localhost:5556

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: my-django-app
    redirectURIs:
      - 'http://localhost:8000/oidc/callback/'
      - 'http://localhost:8000/'
    name: "My Django App"
    secret: my-django-secret #    pragma: allowlist secret
enablePasswordDB: true
staticPasswords:
  - email: "alice@example.gov.uk"
    # bcrypt hash for password "password"
    hash: "$2b$12$O0ojmC7GBIDohHuBFlUQQeEBZSxWEPCCayq43ACYbTqQ8fqrNtuEO"
    username: "alice"
    userID: "1"
  - email: "admin@example.gov.uk"
    # bcrypt hash for password "password"
    hash: "$2b$12$O0ojmC7GBIDohHuBFlUQQeEBZSxWEPCCayq43ACYbTqQ8fqrNtuEO"
    username: "admin"
    userID: "2"
  - email: "other@example.gov.uk"
    # bcrypt hash for password "password"
    hash: "$2b$12$O0ojmC7GBIDohHuBFlUQQeEBZSxWEPCCayq43ACYbTqQ8fqrNtuEO"
    username: "other"
    userID: "3"
  - email: "organisation_user@example.gov.uk"
    # bcrypt hash for password "password"
    hash: "$2b$12$O0ojmC7GBIDohHuBFlUQQeEBZSxWEPCCayq43ACYbTqQ8fqrNtuEO"
    username: "organisation_user"
    userID: "4"
  - email: "organisation_lead@example.gov.uk"
    # bcrypt hash for password "password"
    hash: "$2b$12$O0ojmC7GBIDohHuBFlUQQeEBZSxWEPCCayq43ACYbTqQ8fqrNtuEO"
    username: "organisation_lead"
    userID: "5"
  - email: "cyber_advisor@example.gov.uk"
    # bcrypt hash for password "password"
    hash: "$2b$12$O0ojmC7GBIDohHuBFlUQQeEBZSxWEPCCayq43ACYbTqQ8fqrNtuEO"
    username: "cyber_advisor"
    userID: "6"
