Feature: Assessor can log in and review assessments

  Background:
    Given Organisation "Ministry of Agriculture" of type "ministerial-department" exists with systems "System 1, System 2, System 3"
    And the user "test_assessor@example.com" exists
    And the application is running
    And cookies have been "accepted"
    And User "test_assessor@example.com" has the profile "Independent assurance reviewer" assigned in "Ministry of Agriculture"

  Scenario: Assessor sees System overview
    Given there is a "enhanced" profile assessment  for "System 1", "Ministry of Agriculture", for the period "current" in "submitted" status and data "alice_completed_assessment.json"
    And the user logs in with username  "test_assessor@example.com" and password "password"
    And Think time 1 seconds
    Then they should see page title "My account - test_assessor Review a WebCAF self-assessment - GOV.UK"
    And text with "System 1"
    And they should see a table with header "Sent for review date"
    And they should see a table with header "Review status"
    And they should see a table with header "Action"
    And they should see a table including value "System 1"
    And they should see a table including value "To do"
    When click link with text "Review"
    Then page has heading "Review a WebCAF self-assessment"
    When click link with text "Confirm system overview"
    Then page has heading "System overview"
    And click button with text "Save and continue"

  Scenario: Assessor fills Objective A Managing security risk
    Given there is a "enhanced" profile assessment  for "System 1", "Ministry of Agriculture", for the period "current" in "submitted" status and data "alice_completed_assessment.json"
    And the user logs in with username  "test_assessor@example.com" and password "password"
    And Think time 1 seconds
    Then they should see page title "My account - test_assessor Review a WebCAF self-assessment - GOV.UK"
    And text with "System 1"
    And they should see a table including value "System 1"
    When click link with text "Review"
    Then page has heading "Review a WebCAF self-assessment"
    When click link with text "Confirm system overview"
    Then page has heading "System overview"
    And click button with text "Save and continue"
    When click link with text "Objective A: Managing security risk"
    Then page has heading "Objective A - Managing security risk review and confirmation"
    And text with "A1.a Board Direction"
    When click link in summary card row "A1.a Board Direction" with text "Review"
    Then page has heading "A1.a Board Direction review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"
    When click link in summary card row "A1.b Roles and Responsibilities" with text "Review"
    Then page has heading "A1.b Roles and Responsibilities review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"
    When click link in summary card row "A1.c Decision-making" with text "Review"
    Then page has heading "A1.c Decision-making review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected Senior management have visibility of"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected Risk management decision-makers"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected Risk management decision-making"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected Risk management decisions"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation selected"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"
    When click link in summary card row "A2.a Risk Management Process" with text "Review"
    Then page has heading "A2.a Risk Management Process review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 7 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 8 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 9 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 6 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Risk assessments are not based on"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Risk assessment outputs are too"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Risk assessments for network and"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select The security elements of projects or"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select There is no systematic process in"
    When select radio with label "Yes" in row "Not Achieved statement 6 Organisation did not select Systems are assessed in isolation"
    When select radio with label "Yes" in row "Not Achieved statement 7 Organisation did not select Security requirements and"
    When select radio with label "Yes" in row "Not Achieved statement 8 Organisation did not select Risks remain unresolved on a"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"
    When click link in summary card row "A2.b Assurance" with text "Review"
    Then page has heading "A2.b Assurance review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"
    When click link in summary card row "A3.a Asset Management" with text "Review"
    Then page has heading "A3.a Asset Management review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"
    When click link in summary card row "A4.a Supply Chain" with text "Review"
    Then page has heading "A4.a Supply Chain review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 7 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 6 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You do not know what data"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Elements of the supply chain for"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You have no understanding of which"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Suppliers have access to systems"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # good/improvement
    When click link in summary card row "Areas of good practice" with text "Add comment"
    Then page has heading "Areas of good practice"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    When click link in summary card row "Areas for improvement" with text "Add comment"
    Then page has heading "Areas for improvement"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    When select radio with label "Yes" in fieldset "Do you want to go to the next objective?"
    And click button with text "Save and continue"

    # B1.a Policy, Process and Procedure Development
    When click link in summary card row "B1.a Policy, Process and Procedure Development" with text "Review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Your policies, processes and procedures are absent or incomplete"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Policies, processes and procedures are not applied"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select People often or routinely"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Your organisation's security"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select System security is totally reliant on"
    When select radio with label "Yes" in row "Not Achieved statement 6 Organisation did not select Policies, processes and procedures have"
    When select radio with label "Yes" in row "Not Achieved statement 7 Organisation did not select Policies, processes and procedures are"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B1.b Policy, Process and Procedure Implementation
    When click link in summary card row "B1.b Policy, Process and Procedure Implementation" with text "Review"
    Then page has heading "B1.b Policy, Process and Procedure Implementation review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Policies, processes and procedures"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select How your policies, processes and"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Staff are unaware of their"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select You do not attempt to detect"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Policies, processes and procedures lack"
    When select radio with label "Yes" in row "Not Achieved statement 6 Organisation did not select Your policies, processes and procedures are not well"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B2.a Identity Verification, Authentication and Authorisation
    When click link in summary card row "B2.a Identity Verification, Authentication and Authorisation" with text "Review"
    Then page has heading "B2.a Identity Verification, Authentication and Authorisation review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 6 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 7 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Initial identity verification is not"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Authorised users and systems with"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Unauthorised individuals or devices"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select The number of authorised users and"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Your approach to authenticating"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B2.b Device Management
    When click link in summary card row "B2.b Device Management" with text "Review"
    Then page has heading "B2.b Device Management review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Users can connect to your network"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Privileged users can perform"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You have not gained assurance in"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Physically connecting a device to"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B2.c Privileged User Management
    When click link in summary card row "B2.c Privileged User Management" with text "Review"
    Then page has heading "B2.c Privileged User Management review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select The identities of the individuals with"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Privileged user access to network"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select The list of privileged users has not"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Privileged user access is granted on"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Privileged user access to your"
    When select radio with label "Yes" in row "Not Achieved statement 6 Organisation did not select Where there are"
    When select radio with label "Yes" in row "Not Achieved statement 7 Organisation did not select There is no logical separation"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B2.d Identity and Access Management (IdAM)
    When click link in summary card row "B2.d Identity and Access Management (IdAM)" with text "Review"
    Then page has heading "B2.d Identity and Access Management (IdAM) review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Greater access rights are granted than necessary"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Identity validation and requirement"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select User access rights are not reviewed"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select User access rights remain active"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Access rights granted to devices or"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B3.a Understanding Data
    When click link in summary card row "B3.a Understanding Data" with text "Review"
    Then page has heading "B3.a Understanding Data review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 7 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 8 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 9 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 6 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You have incomplete knowledge of"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You have not identified the"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You have not identified who has"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select You have not clearly articulated the"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B3.b Data in Transit
    When click link in summary card row "B3.b Data in Transit" with text "Review"
    Then page has heading "B3.b Data in Transit review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You do not know what all your data"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Data important to the operation of"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Critical data paths that could fail"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B3.c Stored Data
    When click link in summary card row "B3.c Stored Data" with text "Review"
    Then page has heading "B3.c Stored Data review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You have no, or limited, knowledge"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You have not protected vulnerable"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Backups are incomplete, untested"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B3.d Mobile Data
    When click link in summary card row "B3.d Mobile Data" with text "Review"
    Then page has heading "B3.d Mobile Data review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You don't know which mobile"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You allow data important to the"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Data on mobile devices is not"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B3.e Media / Equipment Sanitisation
    When click link in summary card row "B3.e Media / Equipment Sanitisation" with text "Review"
    Then page has heading "B3.e Media / Equipment Sanitisation review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Some or all devices, equipment"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B4.a Secure by Design
    When click link in summary card row "B4.a Secure by Design" with text "Review"
    Then page has heading "B4.a Secure by Design review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Systems essential to the operation"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Internet access is available from"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Data flows between network"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Remote or third-party accesses"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B4.b Secure Configuration
    When click link in summary card row "B4.b Secure Configuration" with text "Review"
    Then page has heading "B4.b Secure Configuration review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 7 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 8 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 6 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You haven't identified the assets"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Policies relating to the security of"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Configuration details are not"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select The recording of security changes"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Generic, shared, default name"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B4.c Secure Management
    When click link in summary card row "B4.c Secure Management" with text "Review"
    Then page has heading "B4.c Secure Management review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Your systems and devices"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You do not have good or current"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B4.d Vulnerability Management
    When click link in summary card row "B4.d Vulnerability Management" with text "Review"
    Then page has heading "B4.d Vulnerability Management review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You do not understand the exposure"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You do not mitigate externally"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You have not recently tested to"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select You have not suitably mitigated"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select You are not pursuing replacement"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B5.a Resilience Preparation
    When click link in summary card row "B5.a Resilience Preparation" with text "Review"
    Then page has heading "B5.a Resilience Preparation review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You have limited understanding"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You have not completed business"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You have not fully assessed the"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B5.b Design for Resilience
    When click link in summary card row "B5.b Design for Resilience" with text "Review"
    Then page has heading "B5.b Design for Resilience review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Network and information systems"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Internet services, such as browsing"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You do not understand or lack plans"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B5.c Backups
    When click link in summary card row "B5.c Backups" with text "Review"
    Then page has heading "B5.c Backups review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Backup coverage is incomplete"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Backups are not frequent enough"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Your restoration process"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B6.a Cyber Security Culture
    When click link in summary card row "B6.a Cyber Security Culture" with text "Review"
    Then page has heading "B6.a Cyber Security Culture review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select People in your organisation don't understand"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select People in your organisation don't know"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select People believe that reporting issues"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Your organisation's approach to"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # B6.b Cyber Security Training
    When click link in summary card row "B6.b Cyber Security Training" with text "Review"
    Then page has heading "B6.b Cyber Security Training review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select There are teams who operate"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Cyber security training is restricted"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Cyber security training records"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # good/improvement
    When click link in summary card row "Areas of good practice" with text "Add comment"
    Then page has heading "Areas of good practice"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    When click link in summary card row "Areas for improvement" with text "Add comment"
    Then page has heading "Areas for improvement"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    When select radio with label "Yes" in fieldset "Do you want to go to the next objective?"
    And click button with text "Save and continue"

    # C1.a Monitoring Coverage
    When click link in summary card row "C1.a Monitoring Coverage" with text "Review"
    Then page has heading "C1.a Monitoring Coverage review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Data relating to the security "
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You do not confidently detect"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You are not able to audit"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select You do not capture any traffic"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # C1.b Securing Logs
    When click link in summary card row "C1.b Securing Logs" with text "Review"
    Then page has heading "C1.b Securing Logs review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 7 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select It is possible for log data to be easily"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select There is no controlled list of the"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select There is no monitoring of the access to log data."
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select There is no policy for accessing log data"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Log data is not synchronised"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # C1.c Generating Alerts
    When click link in summary card row "C1.c Generating Alerts" with text "Review"
    Then page has heading "C1.c Generating Alerts review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Alerts from third party security"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Logs are distributed across devices"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select The resolution of alerts to a network"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Security alerts relating to essential"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Logs are reviewed infrequently"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # C1.d Identifying Security Incidents
    When click link in summary card row "C1.d Identifying Security Incidents" with text "Review"
    Then page has heading "C1.d Identifying Security Incidents review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Your organisation has no sources"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You do not apply updates in a timely"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select You do not receive signature"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select You do not evaluate the usefulness"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # C1.e Monitoring Tools and Skills
    When click link in summary card row "C1.e Monitoring Tools and Skills" with text "Review"
    Then page has heading "C1.e Monitoring Tools and Skills review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 7 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 5 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 6 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select There are no staff who perform a monitoring function"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Monitoring staff do not have the correct specialist skills"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Monitoring staff are not capable"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Monitoring staff lack the skills"
    When select radio with label "Yes" in row "Not Achieved statement 5 Organisation did not select Monitoring tools are only able "
    When select radio with label "Yes" in row "Not Achieved statement 6 Organisation did not select Monitoring tools cannot"
    When select radio with label "Yes" in row "Not Achieved statement 7 Organisation did not select Monitoring staff have a lack"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # C2.a System Abnormalities for Attack Detection
    When click link in summary card row "C2.a System Abnormalities for Attack Detection" with text "Review"
    Then page has heading "C2.a System Abnormalities for Attack Detection review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Normal system behaviour"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You have no established"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # C2.b Proactive Attack Discovery
    When click link in summary card row "C2.b Proactive Attack Discovery" with text "Review"
    Then page has heading "C2.b Proactive Attack Discovery review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected You routinely"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation selected You do not routinely search"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # good/improvement
    When click link in summary card row "Areas of good practice" with text "Add comment"
    Then page has heading "Areas of good practice"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    When click link in summary card row "Areas for improvement" with text "Add comment"
    Then page has heading "Areas for improvement"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    When select radio with label "Yes" in fieldset "Do you want to go to the next objective?"
    And click button with text "Save and continue"

    # D1.a Response Plan
    When click link in summary card row "D1.a Response Plan" with text "Review"
    Then page has heading "D1.a Response Plan review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Partially Achieved statement 1 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 2 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 3 Organisation did not select"
    When select radio with label "Yes" in row "Partially Achieved statement 4 Organisation did not select"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Your incident response plan is not documented"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Your incident response plan does"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Your incident response plan is not"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # D1.b Response and Recovery Capability
    When click link in summary card row "D1.b Response and Recovery Capability" with text "Review"
    Then page has heading "D1.b Response and Recovery Capability review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 6 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Inadequate arrangements have"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Your response team members"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Inadequate back-up mechanisms"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # D1.c Testing and Exercising
    When click link in summary card row "D1.c Testing and Exercising" with text "Review"
    Then page has heading "D1.c Testing and Exercising review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Exercises test only a discrete part of"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Incident response exercises are not"
    When select radio with label "Yes" in row "Not Achieved statement 3 Organisation did not select Outputs from exercises are not fed"
    When select radio with label "Yes" in row "Not Achieved statement 4 Organisation did not select Exercises do not test all parts of the response cycle"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # D2.a Incident Root Cause Analysis
    When click link in summary card row "D2.a Incident Root Cause Analysis" with text "Review"
    Then page has heading "D2.a Incident Root Cause Analysis review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select You are not usually able to resolve"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select You do not have a formal process"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # D2.b Using Incidents to Drive Improvements
    When click link in summary card row "D2.b Using Incidents to Drive Improvements" with text "Review"
    Then page has heading "D2.b Using Incidents to Drive Improvements review"
    When select radio with label "Yes" in row "Achieved statement 1 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 2 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 3 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 4 Organisation selected"
    When select radio with label "Yes" in row "Achieved statement 5 Organisation selected"
    When select radio with label "Yes" in row "Not Achieved statement 1 Organisation did not select Following incidents, lessons learned"
    When select radio with label "Yes" in row "Not Achieved statement 2 Organisation did not select Improvements arising from lessons"
    When select radio with label "Achieved" in fieldset "Review the contributing outcome"
    When enter text "test" for id "id_review_comment"
    And click button with text "Save and continue"

    # good/improvement
    When click link in summary card row "Areas of good practice" with text "Add comment"
    Then page has heading "Areas of good practice"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    When click link in summary card row "Areas for improvement" with text "Add comment"
    Then page has heading "Areas for improvement"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"
    And click button with text "Back to review draft review"

    # Add review details
    # Enter the Independent Assurance Review (IAR) period
    When click link with text "Enter Independent Assurance Review (IAR) period"
    Then page has heading "Enter the Independent Assurance Review (IAR) period"
    When we enter review dates with start date as today and end date as 2 days from today
    And click button with text "Save and continue"

    # Add company details
    When click link with text "Add company details"
    Then page has heading "Add company details"
    When enter text "test" for id "company_name"
    When enter text "test" for id "lead_assessor_name"
    When enter text "test@company.com" for id "lead_assessor_email"
    And click button with text "Save and continue"

    # Describe your review method
    When click link with text "Describe review method"
    Then page has heading "Describe your review method"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"

    # Describe the quality of the self-assessment
    When click link with text "Describe the quality of the self-assessment"
    Then page has heading "Describe the quality of the self-assessment"
    When enter text "test" for id "id_form-text"
    And click button with text "Save and continue"

    # Create report
    When click link with text "Create report"
    Then page has heading "Create report"
    And click button with text "Save and continue"
    Then page has heading "Your IAR report has been created (Version 1)"
    Then download file by clicking button "Download report (PDF)"
    Then confirm current assessment information is on the downloaded pdf
