name: Build & Publish Docker to ECR (Production)

#Runs on creation of a release tag. Image is deployed to production environment.
#Tag is only considered if it starts with "release-" and from the main branch.
on:
  push:
    tags:
      - "release-*"

permissions:
  id-token: write   # required for AWS OIDC
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Derive image name
        id: image_name
        run: |
          TAG="${GITHUB_REF_NAME}"
          BASE_IMAGE="web-caf-app-ecr"

          echo "Image name is : $BASE_IMAGE"
          echo "IMAGE_NAME=$BASE_IMAGE" >> $GITHUB_OUTPUT

      - name: Ensure release tag is from main
        if: startsWith(github.ref_name, 'release-')
        run: |
          if [ "${GITHUB_EVENT_BASE_REF}" != "refs/heads/main" ]; then
            echo "❌ Release tags must be created from main branch only."
            echo "This tag (${GITHUB_REF_NAME}) came from ${GITHUB_EVENT_BASE_REF}"
            exit 1
          fi
      - name: Configure AWS credentials (Prod)
        if: startsWith(github.ref_name, 'release-')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/github-actions-ecr-role-web-caf-app-ecr
          aws-region: eu-west-2
      - name: Log in to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build, Tag, and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          IMAGE_NAME: ${{ steps.image_name.outputs.IMAGE_NAME }}
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}   # short commit SHA as the tag
          echo "Pushing image: $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
#          Keeping the build step commented out for now. Will be enabled once we have a working infrastructure deployed.
#          docker buildx build --platform linux/amd64 \
#          -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
#          -t $ECR_REGISTRY/$IMAGE_NAME:latest  \
#          . --push;
